version: "3.9"
services:
  api:
    restart: "always"
    build:
      context: "./"
      dockerfile: "Dockerfile"
      args:
        IMAGE_REGISTRY_BASE_URL: ${IMAGE_REGISTRY_BASE_URL}
    ports:
      - "${HTML_TO_PDF_CONVERTER_API_PORT}:${HTML_TO_PDF_CONVERTER_API_PORT}"
    env_file:
      - .env
