services:
  api:
    restart: "always"
    build:
      context: "./"
      dockerfile: "Dockerfile"
      args:
        IMAGE_REGISTRY_BASE_URL: ${IMAGE_REGISTRY_BASE_URL}
    env_file:
      - .env
    environment:
      - API_HOST=0.0.0.0
